name: Testing Algorithms

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Installing dependencies
      run: python3 -m venv venv && . venv/bin/activate)&& pip3 install -r requirements.txt && pip3 install pytest
    - name: Running tests
      run: pytest

